authorization/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="Home"),
    path('register/', views.register, name='register'),
    path('login/', views.CustomerLoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('verify_email/<int:id>', views.verify_email, name='verify_email'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from authorization.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authorization.urls')),
    path('', home, name='home'),
    path('wordgame/', include('wordgame.urls')),

    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

authorization/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomerUser(AbstractUser):
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    auth_code = models.CharField(max_length=10, null=True, blank=True)
    is_active = models.BooleanField(default=False)
    
    def __str__(self):
        return self.username
    
class Country(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(CustomerUser, on_delete=models.CASCADE, related_name="profile")
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    bio = models.TextField(null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=True)
    rating = models.IntegerField(default=0)


    def __str__(self):
        return self.user.username

authorization/forms.py
from django import forms
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


from .models import CustomerUser, Profile

class CustomerUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomerUser
        fields = ('username', 'email', 'phone_number')


class CustomerAuthenticationForm(AuthenticationForm):
    def confirm_login_allowed(self, user):
        if not user.is_active:
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )
        

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'bio', 'birth_date', 'country']
        widgets = {
            'birth_date': forms.DateInput(attrs={'type': 'date'}),
        }

class CustomerUserForm(forms.ModelForm):
    class Meta:
        model = CustomerUser
        fields = ['username', 'email', 'phone_number']

authorization/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView

from wordgame.models import Game

from .forms import CustomerUserCreationForm, CustomerAuthenticationForm, ProfileForm, CustomerUserForm
from .models import Country, CustomerUser
from .utils import send_code_email



def home(request):
    return render(request, 'home.html')

def verify_email(request, id):
    user = CustomerUser.objects.get(id=id)
    if request.method == 'POST':
        code = request.POST.get('code')
        if code == user.auth_code:
            user.is_active = True
            user.save()
            login(request, user)
            return redirect('home')
        else:
            return render(request, 'verify_email.html', {'error': 'Неверный код!'})
    return render(request, 'verify_email.html')

def register(request):
    if request.method == 'POST':
        form = CustomerUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            send_code_email(user)
            return redirect('verify_email', user.id)
    else:
        form = CustomerUserCreationForm()
    return render(request, 'register.html', {'form': form})

class CustomerLoginView(LoginView):
    authentication_form = CustomerAuthenticationForm
    template_name = 'login.html'
    redirect_field_name = 'home'

def logout_view(request):
    logout(request)
    return redirect('home')

@login_required
def profile(request):
    games = Game.objects.filter(user=request.user, completed_at__isnull=False).order_by('-created_at')
    return render(request, 'profile.html', {'games': games})

@login_required
def edit_profile(request):
    user = request.user
    profile = user.profile

    if request.method == 'POST':
        user_form = CustomerUserForm(request.POST, instance=user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('profile')
    else:
        user_form = CustomerUserForm(instance=user)
        profile_form = ProfileForm(instance=profile)
    
    countries = Country.objects.all()
    return render(request, 'authorization/edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'countries': countries,
    })





"""
GET  - Получение 
POST - Отправка
PATCH - Изменения одного из полей или более
PUT - Изменения всех полей
DELETE - Удаление
"""

authorization/templates/authorization/edit_profile.html
{% extends 'base_generic.html' %}

{% block title %}Edit Profile{% endblock %}

{% block content %}
  <div class="container">
    <h2>Edit Profile</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      
      <div class="profile-image">
        {% if user.profile.image %}
          <img src="{{ user.profile.image.url }}" alt="{{ user.username }}">
        {% endif %}
      </div>

      <div class="form-field">
        <label for="id_username">Username:</label>
        <input type="text" name="username" id="id_username" value="{{ user.username }}" placeholder="Имя пользователя">
        {% if form.username.errors %}
          <div class="errorlist">{{ form.username.errors }}</div>
        {% endif %}
      </div>

      <div class="form-field">
        <label for="id_image">Profile Picture:</label>
        <input type="file" name="image" id="id_image">
        {% if form.image.errors %}
          <div class="errorlist">{{ form.image.errors }}</div>
        {% endif %}
      </div>

      <div class="form-field">
        <label for="id_phone_number">Phone Number:</label>
        <input type="text" name="phone_number" id="id_phone_number" value="{{ user.phone_number }}" placeholder="Номер телефона">
        {% if form.phone_number.errors %}
          <div class="errorlist">{{ form.phone_number.errors }}</div>
        {% endif %}
      </div>

      <div class="form-field">
        <label for="id_birth_date">Birth Date:</label>
        <input type="date" name="birth_date" id="id_birth_date" value="{{ user.profile.birth_date|date:'Y-m-d' }}" placeholder="Дата рождения">
        {% if form.birth_date.errors %}
          <div class="errorlist">{{ form.birth_date.errors }}</div>
        {% endif %}
      </div>
      <div class="form-field">
        <label for="id_country">Country:</label>
        <select name="country" id="id_country">
            {% for country in countries %}
                <option value="{{ country.id }}" {% if country.id == user.profile.country.id %}selected{% endif %}>{{ country.name }}</option>
            {% endfor %}
        </select>
        {% if form.country.errors %}
            <div class="errorlist">{{ form.country.errors }}</div>
        {% endif %}
    </div>
    

      <div class="form-field">
        <label for="id_bio">About Me:</label>
        <textarea name="bio" id="id_bio" placeholder="О себе">{{ user.profile.bio }}</textarea>
        {% if form.bio.errors %}
          <div class="errorlist">{{ form.bio.errors }}</div>
        {% endif %}
      </div>

      <button type="submit">Save Changes</button>
    </form>
  </div>
{% endblock %}