core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from authorization.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authorization.urls')),
    path('', home, name='home'),
    path('wordgame/', include('wordgame.urls')),

    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

wordgame/urls.py
# wordgame/urls.py

from django.urls import path
from . import views


urlpatterns = [
    path('', views.game_home, name='game_home'),
    path('win/', views.game_win, name='game_win'),
    path('lose/', views.game_lose, name='game_lose'),
    path('history/', views.game_history, name='game_history'),
    path('history/<int:game_id>/', views.game_detail, name='game_detail'),
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('get_hint/', views.get_hint, name='get_hint')
]

wordgame/models.py
from django.db import models
from authorization.models import CustomerUser

class Word(models.Model):
    word = models.CharField(max_length=5, unique=True)

    def __str__(self):
        return self.word

class Game(models.Model):
    user = models.ForeignKey(CustomerUser, on_delete=models.CASCADE)
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    win = models.BooleanField(default=False)


    def __str__(self):
        return f"{self.user.username} - {self.word}"

class Attempt(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    guessed_word = models.CharField(max_length=5)
    attempts = models.IntegerField(default=6)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.guessed_word} ({self.attempts})"

wordgame/forms.py
# wordgame/forms.py

from django import forms

class GuessWordForm(forms.Form):
    guessed_word = forms.CharField(max_length=5, min_length=5, widget=forms.TextInput(attrs={'class': 'form-control'}))

wordgame/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.http import JsonResponse


from authorization.models import Profile
from .models import Word, Attempt, Game
from .forms import GuessWordForm
from random import choice

def initialize_game(request):
    """Инициализация игры, если она еще не начата."""
    word = Word.objects.order_by('?').first()
    game = Game.objects.create(user=request.user, word=word)
    request.session['game_id'] = game.id
    request.session['attempts'] = 6
    request.session['hints'] = 0
    return game

def get_previous_attempts(game):
    """Получение предыдущих попыток пользователя и форматирование их для отображения."""
    previous_attempts = []
    for attempt in Attempt.objects.filter(game=game):
        previous_attempt = ""
        for i in range(5):
            if attempt.guessed_word[i].lower() == game.word.word[i].lower():
                previous_attempt += f'<input type="text" class="code-input green" value="{attempt.guessed_word[i].upper()}" readonly>'
            elif attempt.guessed_word[i].lower() in game.word.word.lower():
                previous_attempt += f'<input type="text" class="code-input orange" value="{attempt.guessed_word[i].upper()}" readonly>'
            else:
                previous_attempt += f'<input type="text" class="code-input gray" value="{attempt.guessed_word[i].upper()}" readonly>'
        previous_attempts.append(previous_attempt)
    return previous_attempts

def process_post_request(request, form, game, attempts):
    """Обработка POST-запроса: проверка угаданного слова и обновление попыток."""
    if form.is_valid():
        guessed_word = form.cleaned_data['guessed_word']
        attempts -= 1
        request.session['attempts'] = attempts
        
        attempt = Attempt(game=game, guessed_word=guessed_word, attempts=attempts)
        attempt.save()
        
        if guessed_word.lower() == game.word.word.lower():
            return redirect('game_win')

        if attempts <= 0:
            return redirect('game_lose')

        return redirect('game_home')


def get_hint(request):
    game_id = request.session.get('game_id')
    if not game_id:
        return JsonResponse({'status': 'no_game'}, status=400)

    game = get_object_or_404(Game, id=game_id)
    
    hints_used = request.session.get('hints', 0)
    if hints_used >= 1:
        return JsonResponse({'status': 'no_more_hints'}, status=400)
    
    word = game.word.word
    not_guessed = set(word.lower()) - set(''.join([attempt.guessed_word.lower() for attempt in Attempt.objects.filter(game=game)]))
    
    if not not_guessed:
        return JsonResponse({'status': 'no_hint'}, status=400)

    random_letter = choice(list(not_guessed))
    letter_index = word.lower().index(random_letter)
    
    request.session['hints'] = hints_used + 1
    request.user.profile.rating -= 2
    request.user.profile.save()
    return JsonResponse({'letter': random_letter.upper(), 'index': letter_index})
    
    


@login_required
def game_home(request):
    if 'game_id' not in request.session:
        game = initialize_game(request)
    else:
        game = get_object_or_404(Game, id=request.session['game_id'])
    attempts = request.session.get('attempts', 6)
    form = GuessWordForm()
    
    previous_attempts = get_previous_attempts(game)
    

    if request.method == 'POST':
        form = GuessWordForm(request.POST)
        response = process_post_request(request, form, game, attempts)
        if response:
            return response

    return render(request, 'wordgame/game_home.html', {'form': form, 'attempts': attempts, 'word': game.word.word, 'previous_attempts': previous_attempts})

@login_required
def game_win(request):
    game = get_object_or_404(Game, id=request.session['game_id'])
    game.completed_at = timezone.now()
    game.win = True
    game.save()

    profile = request.user.profile
    profile.rating += 5
    profile.save()
    
    request.session.pop('game_id', None)
    request.session.pop('attempts', None)
    return render(request, 'wordgame/game_win.html')

@login_required
def game_lose(request):
    game = get_object_or_404(Game, id=request.session['game_id'])
    game.completed_at = timezone.now()
    game.save()
    word = game.word.word
    request.session.pop('game_id', None)
    request.session.pop('attempts', None)
    return render(request, 'wordgame/game_lose.html', {'word': word})

@login_required
def game_history(request):
    games = Game.objects.filter(user=request.user, completed_at__isnull=False).order_by('-created_at')
    return render(request, 'wordgame/game_history.html', {'games': games})

@login_required
def game_detail(request, game_id):
    game = get_object_or_404(Game, id=game_id, user=request.user)
    attempts = get_previous_attempts(game)
    return render(request, 'wordgame/game_detail.html', {'game': game, 'attempts': attempts})


def leaderboard(request):
    # Получить первые 10 пользователей, отсортированных по рейтингу в убывающем порядке
    top_players = Profile.objects.order_by('-rating')[:100]
    return render(request, 'wordgame/leaderboard.html', {'top_players': top_players})

wordgame/templates/wordgame/game_detail.html
<!-- templates/wordgame/game_detail.html -->

{% extends "base_generic.html" %}

{% block title %}Детали Игры{% endblock %}

{% block content %}
<div class="container">
    <h2>Детали Игры</h2>
    <p>Слово: {{ game.word.word }}</p>
    <p>Дата начала: {{ game.created_at }}</p>
    <p>Дата завершения: {{ game.completed_at }}</p>
    <h3>Попытки</h3>
        {% for attempt in attempts %}
        <div class="code-inputs">
            {{ attempt|safe }}
        </div>
    {% endfor %}
</div>

<style>
.container {
    background-color: white;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    width: 80%;
    max-width: 100%;
    text-align: center;
    margin-top: 50px;
}

.attempt {
    display: flex;
    justify-content: center;
    align-items: center;
    margin-bottom: 10px;
}

.code-input {
    width: 50px;
    height: 50px;
    font-size: 24px;
    text-align: center;
    border: 1px solid #ccc;
    border-radius: 5px;
    margin-right: 5px;
}

.code-input.green {
    background-color: green;
    color: white;
}

.code-input.orange {
    background-color: orange;
    color: white;
}

.code-input.gray {
    background-color: gray;
    color: white;
}

.code-input:last-child {
    margin-right: 0;
}

span {
    margin-left: 10px;
    font-size: 14px;
    color: #666;
}
</style>

{% endblock %}

wordgame/templates/wordgame/game_history.html
<!-- templates/wordgame/game_history.html -->

{% extends "base_generic.html" %}

{% block title %}Game History{% endblock %}

{% block content %}
<div class="container">
    <h2>История Игр</h2>
    <table>
        <thead>
            <tr>
                <th>Время начало</th>
                <th>Слово</th>
                <th>Попытки</th>
                <th>Результат</th>
                <th>Время завершения</th>
            </tr>
        </thead>
        <tbody>
            {% for game in games %}
            <tr>
                <td>{{ game.created_at }}</td>
                <td>{{ game.word.word }}</td>
                <td>{{ game.attempt_set.count }}</td>
                <td>{{ game.completed_at }}</td>
                <td>{% if game.win %}Победа{% else %}Поражение{% endif %}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<style>
.container {
    background-color: white;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    width: 80%;
    max-width: 100%;
    text-align: center;
    margin-top: 50px;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 20px;
}

th, td {
    padding: 10px;
    border: 1px solid #ccc;
    text-align: left;
}

th {
    background-color: #f4f4f4;
}

</style>

{% endblock %}

wordgame/templates/wordgame/game_home.html
<!-- templates/wordgame/game_home.html -->

{% extends "base_generic.html" %}

{% block title %}Guess the Word{% endblock %}

{% block content %}
<div class="container">
    <h2>Угадайте слово</h2>
    <p>У вас осталось {{ attempts }} попыток </p>
    <form method="post">
        {% csrf_token %}
        <div class="code-inputs">
            <input type="text" name="guessed_word1" id="code1" maxlength="1" class="code-input" required>
            <input type="text" name="guessed_word2" id="code2" maxlength="1" class="code-input" required>
            <input type="text" name="guessed_word3" id="code3" maxlength="1" class="code-input" required>
            <input type="text" name="guessed_word4" id="code4" maxlength="1" class="code-input" required>
            <input type="text" name="guessed_word5" id="code5" maxlength="1" class="code-input" required>
        </div>
        <input type="hidden" name="guessed_word" id="guessed_word">
        <button type="submit">Проверить</button>

 {% if attempts <= 5 %}
<button type="button" id="hint-button">Получить подсказку ✨</button>
{% endif %}

<div id="hint-box" style="display:none;">
    <p>Подсказка: Буква <span id="hint-letter"></span> находится на позиции <span id="hint-position"></span></p>
</div>
    </form>
    

    {% if previous_attempts %} <h3>Предыдущие попытки</h3>{% endif %}
    
    {% for attempt in previous_attempts %}
        <div class="code-inputs">
            {{ attempt|safe }}
        </div>
    {% endfor %}

</div>


<script>
    document.addEventListener("DOMContentLoaded", function() {
        const codeInputs = document.querySelectorAll(".code-input");
        const hiddenGuessedWordInput = document.getElementById("guessed_word");
    
        // Ограничиваем коллекцию только первыми пятью инпутами
        const firstFiveInputs = Array.from(codeInputs).slice(0, 5);
    
        firstFiveInputs.forEach((input, index) => {
            input.addEventListener("input", () => {
                if (input.value.length === 1 && index < firstFiveInputs.length - 1) {
                    firstFiveInputs[index + 1].focus();
                }
                updateHiddenGuessedWordInput();
            });
    
            input.addEventListener("keydown", (event) => {
                if (event.key === "Backspace" && input.value.length === 0 && index > 0) {
                    firstFiveInputs[index - 1].focus();
                }
            });
        });
    
        function updateHiddenGuessedWordInput() {
            let guessedWordValue = "";
            firstFiveInputs.forEach(input => {
                guessedWordValue += input.value;
            });
            hiddenGuessedWordInput.value = guessedWordValue;
        }
    
        // Логика подсказки
        const hintButton = document.getElementById("hint-button");
    const hintBox = document.getElementById("hint-box");
    const hintLetter = document.getElementById("hint-letter");
    const hintPosition = document.getElementById("hint-position");

    if (hintButton) {
        hintButton.addEventListener("click", function() {
            fetch("{% url 'get_hint' %}", {
                method: "POST",
                headers: {
                    "X-CSRFToken": "{{ csrf_token }}",
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({}),
            })
            .then(response => response.json())
            .then(data => {
                if (data.status === 'no_more_hints') {
                    alert("Вы исчерпали все доступные подсказки.");
                } else if (data.status !== 'no_hint') {
                    hintLetter.textContent = data.letter;
                    hintPosition.textContent = data.index + 1;  // Позиция для пользователя начинается с 1
                    hintBox.style.display = "block";
                    }
                })
                .catch(error => {
                    console.error("Ошибка получения подсказки:", error);
                });
            });
        }
    });
    
    
    
    $(document).ready(function() {
        $('form').submit(function(event) {
            // Предотвращаем стандартное поведение отправки формы
            event.preventDefault();
    
            // Получаем данные формы
            var formData = $(this).serialize();
    
            // Отправляем AJAX-запрос
            $.ajax({
                type: 'POST',
                url: $(this).attr('action'),
                data: formData,
                success: function(response) {
                    // Здесь можно обработать успешный ответ от сервера
                    console.log(response);
                    // Например, обновить содержимое страницы или показать сообщение об успешной отправке
                },
                error: function(xhr, status, error) {
                    // Здесь можно обработать ошибку при отправке запроса
                    console.error(xhr.responseText);
                }
            });
        });
    });
</script>

<style>
/* Добавим стили для центрирования и красивого отображения */
.container {
    background-color: white;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    width: 500px;
    max-width: 100%;
    text-align: center;
    margin-top: 50px;
}

.code-inputs {
    display: flex;
    justify-content: space-between;
    margin-bottom: 10px;
}

.code-input {
    width: 50px;
    height: 50px;
    font-size: 24px;
    text-align: center;
    border: 1px solid #ccc;
    border-radius: 5px;
    margin-right: 5px;
}

.code-input:last-child {
    margin-right: 0;
}

form button {
    background-color: #6a11cb;
    color: white;
    padding: 10px;
    border: none;
    border-radius: 5px;
    font-size: 16px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

form button:hover {
    background-color: #2575fc;
}

h4 {
    color: #ff3d3d;
}
.green {
    color: rgb(0, 193, 0);
}

.orange {
    color: rgb(255, 188, 62);
}

.gray {
    color: gray;
}

</style>


{% endblock %}

wordgame/templates/wordgame/game_lose.html
<!-- templates/wordgame/game_lose.html -->

{% extends "base_generic.html" %}

{% block title %}You Lose{% endblock %}

{% block content %}
<div class="container">
    <h2>Вы потратили все попытки. Загаданное "{{ word }}".</h2>
    <form action="{% url 'game_home' %}">
        <button type="submit">Начать заново</button>
    </form>
</div>
{% endblock %}

wordgame/templates/wordgame/game_win.html
<!-- templates/wordgame/game_win.html -->

{% extends "base_generic.html" %}

{% block title %}You Win{% endblock %}

{% block content %}
<div class="container">
    <h2>Поздравляем! Вы угодали слово!</h2>
    <form action="{% url 'game_home' %}">
        <button type="submit">Начать заново</button>
    </form>
</div>
{% endblock %}

wordgame/templates/wordgame/leaderboard.html
<!-- templates/wordgame/game_history.html -->

{% extends "base_generic.html" %}

{% block title %}Game History{% endblock %}

{% block content %}
<div class="container">
    <h2>История Игр</h2>
    <table>
        <thead>
            <tr>
                <th>Имя</th>
                <th>Рейтинг 🏆</th>
                <th>Страна</th>
            </tr>
        </thead>
        <tbody>
            {% for player in top_players %}
            <tr>
                <td>{{ player.user.username }}</td>
                <td>{{ player.rating }} 🏆</td>
                <td>{{ player.country }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<style>
.container {
    background-color: white;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    width: 80%;
    max-width: 100%;
    text-align: center;
    margin-top: 50px;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 20px;
}

th, td {
    padding: 10px;
    border: 1px solid #ccc;
    text-align: left;
}

th {
    background-color: #f4f4f4;
}

</style>

{% endblock %}